"""fix user foreign keys

Revision ID: df1a51ff1427
Revises: 047b08c525ae
Create Date: 2026-02-01 08:55:45.687143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df1a51ff1427'
down_revision: Union[str, Sequence[str], None] = '047b08c525ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_embeddings')
    op.drop_table('chat_sessions')
    op.drop_table('subjects')
    op.drop_table('chat_messages')
    op.drop_table('chapters')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('document_chunks')
    op.drop_table('exams')
    op.drop_table('questions')
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], name='documents_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='documents_subject_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name='documents_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('document_id', name='documents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('questions',
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stem', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], name='questions_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='questions_subject_id_fkey'),
    sa.PrimaryKeyConstraint('question_id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('board', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('starting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('exam_id', name='exams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('start_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='document_chunks_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name='document_chunks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attempts',
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_spent_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hint_level_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempt_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('attempts_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('attempts_pkey'))
    )
    op.create_table('chapters',
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chapter_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='chapters_subject_id_fkey'),
    sa.PrimaryKeyConstraint('chapter_id', name='chapters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], name=op.f('chat_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('chat_messages_pkey'))
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_mark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pass_mark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('theory_mark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('practical_mark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name='subjects_exam_id_fkey'),
    sa.PrimaryKeyConstraint('subject_id', name='subjects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], name=op.f('chat_sessions_chapter_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('chat_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('chat_sessions_pkey'))
    )
    op.create_table('chunk_embeddings',
    sa.Column('embedding_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], name=op.f('chunk_embeddings_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id', name=op.f('chunk_embeddings_pkey')),
    sa.UniqueConstraint('chunk_id', name=op.f('chunk_embeddings_chunk_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
