"""Add enhanced content management tables

Revision ID: f4002c730af9
Revises: 
Create Date: 2026-01-25 13:01:35.385072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4002c730af9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('vector_store_id', sa.String(length=100), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=True),
    sa.Column('embeddings_created', sa.Boolean(), nullable=True),
    sa.Column('access_type', sa.String(length=50), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=True),
    sa.Column('unhelpful_votes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_type_status', 'content', ['content_type', 'processing_status'], unique=False)
    op.create_index(op.f('ix_content_content_type'), 'content', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_created_at'), 'content', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_processing_status'), 'content', ['processing_status'], unique=False)
    op.create_index(op.f('ix_content_title'), 'content', ['title'], unique=False)
    op.create_index(op.f('ix_content_vector_store_id'), 'content', ['vector_store_id'], unique=False)
    op.create_table('curriculum_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['curriculum_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_curriculum_active_type', 'curriculum_nodes', ['active', 'node_type'], unique=False)
    op.create_index('idx_curriculum_parent', 'curriculum_nodes', ['parent_id', 'order_num'], unique=False)
    op.create_index(op.f('ix_curriculum_nodes_active'), 'curriculum_nodes', ['active'], unique=False)
    op.create_index(op.f('ix_curriculum_nodes_code'), 'curriculum_nodes', ['code'], unique=True)
    op.create_index(op.f('ix_curriculum_nodes_node_type'), 'curriculum_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_curriculum_nodes_parent_id'), 'curriculum_nodes', ['parent_id'], unique=False)
    op.create_table('content_curriculum_mapping',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_node_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('mapping_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curriculum_node_id'], ['curriculum_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'curriculum_node_id')
    )
    op.create_index('idx_mapping_content', 'content_curriculum_mapping', ['content_id'], unique=False)
    op.create_index('idx_mapping_curriculum', 'content_curriculum_mapping', ['curriculum_node_id', 'relevance_score'], unique=False)
    op.create_table('exam_specifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('curriculum_node_id', sa.UUID(), nullable=False),
    sa.Column('spec_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_node_id'], ['curriculum_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spec_active_year', 'exam_specifications', ['active', 'year', 'spec_type'], unique=False)
    op.create_index('idx_spec_curriculum', 'exam_specifications', ['curriculum_node_id', 'active'], unique=False)
    op.create_index(op.f('ix_exam_specifications_active'), 'exam_specifications', ['active'], unique=False)
    op.create_index(op.f('ix_exam_specifications_curriculum_node_id'), 'exam_specifications', ['curriculum_node_id'], unique=False)
    op.create_index(op.f('ix_exam_specifications_spec_type'), 'exam_specifications', ['spec_type'], unique=False)
    op.create_index(op.f('ix_exam_specifications_year'), 'exam_specifications', ['year'], unique=False)
    op.create_table('extracted_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_number', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('cognitive_level', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_chapter', 'extracted_items', ['chapter', 'marks'], unique=False)
    op.create_index('idx_item_classification', 'extracted_items', ['item_type', 'cognitive_level', 'difficulty'], unique=False)
    op.create_index(op.f('ix_extracted_items_chapter'), 'extracted_items', ['chapter'], unique=False)
    op.create_index(op.f('ix_extracted_items_cognitive_level'), 'extracted_items', ['cognitive_level'], unique=False)
    op.create_index(op.f('ix_extracted_items_content_id'), 'extracted_items', ['content_id'], unique=False)
    op.create_index(op.f('ix_extracted_items_difficulty'), 'extracted_items', ['difficulty'], unique=False)
    op.create_index(op.f('ix_extracted_items_item_type'), 'extracted_items', ['item_type'], unique=False)
    op.create_table('processing_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False, comment='Which content is being processed'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='Type: extract_text, generate_embeddings, extract_items, quality_check, thumbnail_generation'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Status: pending, processing, completed, failed'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Priority for task execution (1=low, 10=urgent)'),
    sa.Column('progress', sa.Float(), nullable=True, comment='Percentage complete (0.0 to 100.0)'),
    sa.Column('result', sa.JSON(), nullable=True, comment="Task results stored as JSON (e.g., {'chunks_created': 42, 'embeddings': 42})"),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if task failed'),
    sa.Column('attempts', sa.Integer(), nullable=True, comment='Number of times this task has been attempted'),
    sa.Column('max_attempts', sa.Integer(), nullable=True, comment='Maximum retry attempts before giving up'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='When task was queued'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When processing actually started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When task finished (success or failure)'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_queue_status_priority', 'processing_queue', ['status', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_processing_queue_content_id'), 'processing_queue', ['content_id'], unique=False)
    op.create_index(op.f('ix_processing_queue_created_at'), 'processing_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_queue_status'), 'processing_queue', ['status'], unique=False)
    op.create_index(op.f('ix_processing_queue_task_type'), 'processing_queue', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_queue_task_type'), table_name='processing_queue')
    op.drop_index(op.f('ix_processing_queue_status'), table_name='processing_queue')
    op.drop_index(op.f('ix_processing_queue_created_at'), table_name='processing_queue')
    op.drop_index(op.f('ix_processing_queue_content_id'), table_name='processing_queue')
    op.drop_index('idx_queue_status_priority', table_name='processing_queue')
    op.drop_table('processing_queue')
    op.drop_index(op.f('ix_extracted_items_item_type'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_difficulty'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_content_id'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_cognitive_level'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_chapter'), table_name='extracted_items')
    op.drop_index('idx_item_classification', table_name='extracted_items')
    op.drop_index('idx_item_chapter', table_name='extracted_items')
    op.drop_table('extracted_items')
    op.drop_index(op.f('ix_exam_specifications_year'), table_name='exam_specifications')
    op.drop_index(op.f('ix_exam_specifications_spec_type'), table_name='exam_specifications')
    op.drop_index(op.f('ix_exam_specifications_curriculum_node_id'), table_name='exam_specifications')
    op.drop_index(op.f('ix_exam_specifications_active'), table_name='exam_specifications')
    op.drop_index('idx_spec_curriculum', table_name='exam_specifications')
    op.drop_index('idx_spec_active_year', table_name='exam_specifications')
    op.drop_table('exam_specifications')
    op.drop_index('idx_mapping_curriculum', table_name='content_curriculum_mapping')
    op.drop_index('idx_mapping_content', table_name='content_curriculum_mapping')
    op.drop_table('content_curriculum_mapping')
    op.drop_index(op.f('ix_curriculum_nodes_parent_id'), table_name='curriculum_nodes')
    op.drop_index(op.f('ix_curriculum_nodes_node_type'), table_name='curriculum_nodes')
    op.drop_index(op.f('ix_curriculum_nodes_code'), table_name='curriculum_nodes')
    op.drop_index(op.f('ix_curriculum_nodes_active'), table_name='curriculum_nodes')
    op.drop_index('idx_curriculum_parent', table_name='curriculum_nodes')
    op.drop_index('idx_curriculum_active_type', table_name='curriculum_nodes')
    op.drop_table('curriculum_nodes')
    op.drop_index(op.f('ix_content_vector_store_id'), table_name='content')
    op.drop_index(op.f('ix_content_title'), table_name='content')
    op.drop_index(op.f('ix_content_processing_status'), table_name='content')
    op.drop_index(op.f('ix_content_created_at'), table_name='content')
    op.drop_index(op.f('ix_content_content_type'), table_name='content')
    op.drop_index('idx_content_type_status', table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
